name: core
description: A new Flutter package for riverpod movie app
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  sembast: ^3.5.0+1
  transparent_image: ^2.0.1
  dio: ^5.3.3
  envied: ^0.3.0+3


dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3

flutter: null